// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pricecomparison.proto
// </auto-generated>
// Original file comments:
// Single Sign On API
// version: 1
// date: 2019-4-11
// For Price Comparison Access
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Msyrpc {
  public static partial class PriceComparisonService
  {
    static readonly string __ServiceName = "msyrpc.PriceComparisonService";

    static readonly grpc::Marshaller<global::Msyrpc.GetAllCategoryTypesRequest> __Marshaller_msyrpc_GetAllCategoryTypesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetAllCategoryTypesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AllCategoryTypesResponse> __Marshaller_msyrpc_AllCategoryTypesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AllCategoryTypesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.GetAllNewCategoryTypesRequest> __Marshaller_msyrpc_GetAllNewCategoryTypesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetAllNewCategoryTypesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AllNewCategoryTypesResponse> __Marshaller_msyrpc_AllNewCategoryTypesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AllNewCategoryTypesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.GetAllCompetitorTypesRequest> __Marshaller_msyrpc_GetAllCompetitorTypesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetAllCompetitorTypesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AllCompetitorTypesResponse> __Marshaller_msyrpc_AllCompetitorTypesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AllCompetitorTypesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.GetProductComparisonRequest> __Marshaller_msyrpc_GetProductComparisonRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetProductComparisonRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.ProductComparisonResponse> __Marshaller_msyrpc_ProductComparisonResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.ProductComparisonResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateProductDescriptionRequest> __Marshaller_msyrpc_UpdateProductDescriptionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateProductDescriptionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateProductDescriptionResponse> __Marshaller_msyrpc_UpdateProductDescriptionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateProductDescriptionResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateCompetitorTierRequest> __Marshaller_msyrpc_UpdateCompetitorTierRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateCompetitorTierRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateCompetitorTierResponse> __Marshaller_msyrpc_UpdateCompetitorTierResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateCompetitorTierResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.DeleteCompetitorRequest> __Marshaller_msyrpc_DeleteCompetitorRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.DeleteCompetitorRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.DeleteCompetitorResponse> __Marshaller_msyrpc_DeleteCompetitorResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.DeleteCompetitorResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AddCompetitorRequest> __Marshaller_msyrpc_AddCompetitorRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AddCompetitorRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AddCompetitorResponse> __Marshaller_msyrpc_AddCompetitorResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AddCompetitorResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AllStateCategoryTypesRequest> __Marshaller_msyrpc_AllStateCategoryTypesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AllStateCategoryTypesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AllStateCategoryTypesResponse> __Marshaller_msyrpc_AllStateCategoryTypesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AllStateCategoryTypesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateCategoryStateRequest> __Marshaller_msyrpc_UpdateCategoryStateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateCategoryStateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.UpdateCategoryStateResponse> __Marshaller_msyrpc_UpdateCategoryStateResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.UpdateCategoryStateResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.GetCategoryMarginRequest> __Marshaller_msyrpc_GetCategoryMarginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetCategoryMarginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.GetCategoryMarginResponse> __Marshaller_msyrpc_GetCategoryMarginResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.GetCategoryMarginResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AddCategoryMarginRequest> __Marshaller_msyrpc_AddCategoryMarginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AddCategoryMarginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.AddCategoryMarginResponse> __Marshaller_msyrpc_AddCategoryMarginResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.AddCategoryMarginResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.DeleteCategoryMarginRequest> __Marshaller_msyrpc_DeleteCategoryMarginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.DeleteCategoryMarginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Msyrpc.DeleteCategoryMarginResponse> __Marshaller_msyrpc_DeleteCategoryMarginResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Msyrpc.DeleteCategoryMarginResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Msyrpc.GetAllCategoryTypesRequest, global::Msyrpc.AllCategoryTypesResponse> __Method_GetAllProductCategories = new grpc::Method<global::Msyrpc.GetAllCategoryTypesRequest, global::Msyrpc.AllCategoryTypesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllProductCategories",
        __Marshaller_msyrpc_GetAllCategoryTypesRequest,
        __Marshaller_msyrpc_AllCategoryTypesResponse);

    static readonly grpc::Method<global::Msyrpc.GetAllNewCategoryTypesRequest, global::Msyrpc.AllNewCategoryTypesResponse> __Method_GetAllNewCategoryTypes = new grpc::Method<global::Msyrpc.GetAllNewCategoryTypesRequest, global::Msyrpc.AllNewCategoryTypesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllNewCategoryTypes",
        __Marshaller_msyrpc_GetAllNewCategoryTypesRequest,
        __Marshaller_msyrpc_AllNewCategoryTypesResponse);

    static readonly grpc::Method<global::Msyrpc.GetAllCompetitorTypesRequest, global::Msyrpc.AllCompetitorTypesResponse> __Method_GetAllCompetitors = new grpc::Method<global::Msyrpc.GetAllCompetitorTypesRequest, global::Msyrpc.AllCompetitorTypesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllCompetitors",
        __Marshaller_msyrpc_GetAllCompetitorTypesRequest,
        __Marshaller_msyrpc_AllCompetitorTypesResponse);

    static readonly grpc::Method<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse> __Method_GetLoadProductComparisonInfomation = new grpc::Method<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLoadProductComparisonInfomation",
        __Marshaller_msyrpc_GetProductComparisonRequest,
        __Marshaller_msyrpc_ProductComparisonResponse);

    static readonly grpc::Method<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse> __Method_GetLoadFilteredProductComparisonInfomation = new grpc::Method<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLoadFilteredProductComparisonInfomation",
        __Marshaller_msyrpc_GetProductComparisonRequest,
        __Marshaller_msyrpc_ProductComparisonResponse);

    static readonly grpc::Method<global::Msyrpc.UpdateProductDescriptionRequest, global::Msyrpc.UpdateProductDescriptionResponse> __Method_UpdateProductDescription = new grpc::Method<global::Msyrpc.UpdateProductDescriptionRequest, global::Msyrpc.UpdateProductDescriptionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateProductDescription",
        __Marshaller_msyrpc_UpdateProductDescriptionRequest,
        __Marshaller_msyrpc_UpdateProductDescriptionResponse);

    static readonly grpc::Method<global::Msyrpc.UpdateCompetitorTierRequest, global::Msyrpc.UpdateCompetitorTierResponse> __Method_UpdateCompetitorTier = new grpc::Method<global::Msyrpc.UpdateCompetitorTierRequest, global::Msyrpc.UpdateCompetitorTierResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateCompetitorTier",
        __Marshaller_msyrpc_UpdateCompetitorTierRequest,
        __Marshaller_msyrpc_UpdateCompetitorTierResponse);

    static readonly grpc::Method<global::Msyrpc.DeleteCompetitorRequest, global::Msyrpc.DeleteCompetitorResponse> __Method_DeleteCompetitor = new grpc::Method<global::Msyrpc.DeleteCompetitorRequest, global::Msyrpc.DeleteCompetitorResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCompetitor",
        __Marshaller_msyrpc_DeleteCompetitorRequest,
        __Marshaller_msyrpc_DeleteCompetitorResponse);

    static readonly grpc::Method<global::Msyrpc.AddCompetitorRequest, global::Msyrpc.AddCompetitorResponse> __Method_AddCompetitor = new grpc::Method<global::Msyrpc.AddCompetitorRequest, global::Msyrpc.AddCompetitorResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddCompetitor",
        __Marshaller_msyrpc_AddCompetitorRequest,
        __Marshaller_msyrpc_AddCompetitorResponse);

    static readonly grpc::Method<global::Msyrpc.AllStateCategoryTypesRequest, global::Msyrpc.AllStateCategoryTypesResponse> __Method_GetAllStateProductCategories = new grpc::Method<global::Msyrpc.AllStateCategoryTypesRequest, global::Msyrpc.AllStateCategoryTypesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllStateProductCategories",
        __Marshaller_msyrpc_AllStateCategoryTypesRequest,
        __Marshaller_msyrpc_AllStateCategoryTypesResponse);

    static readonly grpc::Method<global::Msyrpc.UpdateCategoryStateRequest, global::Msyrpc.UpdateCategoryStateResponse> __Method_UpdateCategoryState = new grpc::Method<global::Msyrpc.UpdateCategoryStateRequest, global::Msyrpc.UpdateCategoryStateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateCategoryState",
        __Marshaller_msyrpc_UpdateCategoryStateRequest,
        __Marshaller_msyrpc_UpdateCategoryStateResponse);

    static readonly grpc::Method<global::Msyrpc.GetCategoryMarginRequest, global::Msyrpc.GetCategoryMarginResponse> __Method_GetCategoryMargin = new grpc::Method<global::Msyrpc.GetCategoryMarginRequest, global::Msyrpc.GetCategoryMarginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCategoryMargin",
        __Marshaller_msyrpc_GetCategoryMarginRequest,
        __Marshaller_msyrpc_GetCategoryMarginResponse);

    static readonly grpc::Method<global::Msyrpc.AddCategoryMarginRequest, global::Msyrpc.AddCategoryMarginResponse> __Method_AddCategoryMargin = new grpc::Method<global::Msyrpc.AddCategoryMarginRequest, global::Msyrpc.AddCategoryMarginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddCategoryMargin",
        __Marshaller_msyrpc_AddCategoryMarginRequest,
        __Marshaller_msyrpc_AddCategoryMarginResponse);

    static readonly grpc::Method<global::Msyrpc.DeleteCategoryMarginRequest, global::Msyrpc.DeleteCategoryMarginResponse> __Method_DeleteCategoryMargin = new grpc::Method<global::Msyrpc.DeleteCategoryMarginRequest, global::Msyrpc.DeleteCategoryMarginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCategoryMargin",
        __Marshaller_msyrpc_DeleteCategoryMarginRequest,
        __Marshaller_msyrpc_DeleteCategoryMarginResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Msyrpc.PricecomparisonReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PriceComparisonService</summary>
    public abstract partial class PriceComparisonServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AllCategoryTypesResponse> GetAllProductCategories(global::Msyrpc.GetAllCategoryTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AllNewCategoryTypesResponse> GetAllNewCategoryTypes(global::Msyrpc.GetAllNewCategoryTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AllCompetitorTypesResponse> GetAllCompetitors(global::Msyrpc.GetAllCompetitorTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.ProductComparisonResponse> GetLoadProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.ProductComparisonResponse> GetLoadFilteredProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.UpdateProductDescriptionResponse> UpdateProductDescription(global::Msyrpc.UpdateProductDescriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.UpdateCompetitorTierResponse> UpdateCompetitorTier(global::Msyrpc.UpdateCompetitorTierRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.DeleteCompetitorResponse> DeleteCompetitor(global::Msyrpc.DeleteCompetitorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AddCompetitorResponse> AddCompetitor(global::Msyrpc.AddCompetitorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AllStateCategoryTypesResponse> GetAllStateProductCategories(global::Msyrpc.AllStateCategoryTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.UpdateCategoryStateResponse> UpdateCategoryState(global::Msyrpc.UpdateCategoryStateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.GetCategoryMarginResponse> GetCategoryMargin(global::Msyrpc.GetCategoryMarginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.AddCategoryMarginResponse> AddCategoryMargin(global::Msyrpc.AddCategoryMarginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Msyrpc.DeleteCategoryMarginResponse> DeleteCategoryMargin(global::Msyrpc.DeleteCategoryMarginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PriceComparisonService</summary>
    public partial class PriceComparisonServiceClient : grpc::ClientBase<PriceComparisonServiceClient>
    {
      /// <summary>Creates a new client for PriceComparisonService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PriceComparisonServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PriceComparisonService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PriceComparisonServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PriceComparisonServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PriceComparisonServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Msyrpc.AllCategoryTypesResponse GetAllProductCategories(global::Msyrpc.GetAllCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllProductCategories(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AllCategoryTypesResponse GetAllProductCategories(global::Msyrpc.GetAllCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllProductCategories, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllCategoryTypesResponse> GetAllProductCategoriesAsync(global::Msyrpc.GetAllCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllProductCategoriesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllCategoryTypesResponse> GetAllProductCategoriesAsync(global::Msyrpc.GetAllCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllProductCategories, null, options, request);
      }
      public virtual global::Msyrpc.AllNewCategoryTypesResponse GetAllNewCategoryTypes(global::Msyrpc.GetAllNewCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllNewCategoryTypes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AllNewCategoryTypesResponse GetAllNewCategoryTypes(global::Msyrpc.GetAllNewCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllNewCategoryTypes, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllNewCategoryTypesResponse> GetAllNewCategoryTypesAsync(global::Msyrpc.GetAllNewCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllNewCategoryTypesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllNewCategoryTypesResponse> GetAllNewCategoryTypesAsync(global::Msyrpc.GetAllNewCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllNewCategoryTypes, null, options, request);
      }
      public virtual global::Msyrpc.AllCompetitorTypesResponse GetAllCompetitors(global::Msyrpc.GetAllCompetitorTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllCompetitors(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AllCompetitorTypesResponse GetAllCompetitors(global::Msyrpc.GetAllCompetitorTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllCompetitors, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllCompetitorTypesResponse> GetAllCompetitorsAsync(global::Msyrpc.GetAllCompetitorTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllCompetitorsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllCompetitorTypesResponse> GetAllCompetitorsAsync(global::Msyrpc.GetAllCompetitorTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllCompetitors, null, options, request);
      }
      public virtual global::Msyrpc.ProductComparisonResponse GetLoadProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoadProductComparisonInfomation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.ProductComparisonResponse GetLoadProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLoadProductComparisonInfomation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.ProductComparisonResponse> GetLoadProductComparisonInfomationAsync(global::Msyrpc.GetProductComparisonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoadProductComparisonInfomationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.ProductComparisonResponse> GetLoadProductComparisonInfomationAsync(global::Msyrpc.GetProductComparisonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLoadProductComparisonInfomation, null, options, request);
      }
      public virtual global::Msyrpc.ProductComparisonResponse GetLoadFilteredProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoadFilteredProductComparisonInfomation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.ProductComparisonResponse GetLoadFilteredProductComparisonInfomation(global::Msyrpc.GetProductComparisonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLoadFilteredProductComparisonInfomation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.ProductComparisonResponse> GetLoadFilteredProductComparisonInfomationAsync(global::Msyrpc.GetProductComparisonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoadFilteredProductComparisonInfomationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.ProductComparisonResponse> GetLoadFilteredProductComparisonInfomationAsync(global::Msyrpc.GetProductComparisonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLoadFilteredProductComparisonInfomation, null, options, request);
      }
      public virtual global::Msyrpc.UpdateProductDescriptionResponse UpdateProductDescription(global::Msyrpc.UpdateProductDescriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateProductDescription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.UpdateProductDescriptionResponse UpdateProductDescription(global::Msyrpc.UpdateProductDescriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateProductDescription, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateProductDescriptionResponse> UpdateProductDescriptionAsync(global::Msyrpc.UpdateProductDescriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateProductDescriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateProductDescriptionResponse> UpdateProductDescriptionAsync(global::Msyrpc.UpdateProductDescriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateProductDescription, null, options, request);
      }
      public virtual global::Msyrpc.UpdateCompetitorTierResponse UpdateCompetitorTier(global::Msyrpc.UpdateCompetitorTierRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCompetitorTier(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.UpdateCompetitorTierResponse UpdateCompetitorTier(global::Msyrpc.UpdateCompetitorTierRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCompetitorTier, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateCompetitorTierResponse> UpdateCompetitorTierAsync(global::Msyrpc.UpdateCompetitorTierRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCompetitorTierAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateCompetitorTierResponse> UpdateCompetitorTierAsync(global::Msyrpc.UpdateCompetitorTierRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCompetitorTier, null, options, request);
      }
      public virtual global::Msyrpc.DeleteCompetitorResponse DeleteCompetitor(global::Msyrpc.DeleteCompetitorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCompetitor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.DeleteCompetitorResponse DeleteCompetitor(global::Msyrpc.DeleteCompetitorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCompetitor, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.DeleteCompetitorResponse> DeleteCompetitorAsync(global::Msyrpc.DeleteCompetitorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCompetitorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.DeleteCompetitorResponse> DeleteCompetitorAsync(global::Msyrpc.DeleteCompetitorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCompetitor, null, options, request);
      }
      public virtual global::Msyrpc.AddCompetitorResponse AddCompetitor(global::Msyrpc.AddCompetitorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCompetitor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AddCompetitorResponse AddCompetitor(global::Msyrpc.AddCompetitorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddCompetitor, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AddCompetitorResponse> AddCompetitorAsync(global::Msyrpc.AddCompetitorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCompetitorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AddCompetitorResponse> AddCompetitorAsync(global::Msyrpc.AddCompetitorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddCompetitor, null, options, request);
      }
      public virtual global::Msyrpc.AllStateCategoryTypesResponse GetAllStateProductCategories(global::Msyrpc.AllStateCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllStateProductCategories(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AllStateCategoryTypesResponse GetAllStateProductCategories(global::Msyrpc.AllStateCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllStateProductCategories, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllStateCategoryTypesResponse> GetAllStateProductCategoriesAsync(global::Msyrpc.AllStateCategoryTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllStateProductCategoriesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AllStateCategoryTypesResponse> GetAllStateProductCategoriesAsync(global::Msyrpc.AllStateCategoryTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllStateProductCategories, null, options, request);
      }
      public virtual global::Msyrpc.UpdateCategoryStateResponse UpdateCategoryState(global::Msyrpc.UpdateCategoryStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCategoryState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.UpdateCategoryStateResponse UpdateCategoryState(global::Msyrpc.UpdateCategoryStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCategoryState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateCategoryStateResponse> UpdateCategoryStateAsync(global::Msyrpc.UpdateCategoryStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCategoryStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.UpdateCategoryStateResponse> UpdateCategoryStateAsync(global::Msyrpc.UpdateCategoryStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCategoryState, null, options, request);
      }
      public virtual global::Msyrpc.GetCategoryMarginResponse GetCategoryMargin(global::Msyrpc.GetCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCategoryMargin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.GetCategoryMarginResponse GetCategoryMargin(global::Msyrpc.GetCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCategoryMargin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.GetCategoryMarginResponse> GetCategoryMarginAsync(global::Msyrpc.GetCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCategoryMarginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.GetCategoryMarginResponse> GetCategoryMarginAsync(global::Msyrpc.GetCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCategoryMargin, null, options, request);
      }
      public virtual global::Msyrpc.AddCategoryMarginResponse AddCategoryMargin(global::Msyrpc.AddCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCategoryMargin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.AddCategoryMarginResponse AddCategoryMargin(global::Msyrpc.AddCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddCategoryMargin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AddCategoryMarginResponse> AddCategoryMarginAsync(global::Msyrpc.AddCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCategoryMarginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.AddCategoryMarginResponse> AddCategoryMarginAsync(global::Msyrpc.AddCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddCategoryMargin, null, options, request);
      }
      public virtual global::Msyrpc.DeleteCategoryMarginResponse DeleteCategoryMargin(global::Msyrpc.DeleteCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCategoryMargin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Msyrpc.DeleteCategoryMarginResponse DeleteCategoryMargin(global::Msyrpc.DeleteCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCategoryMargin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.DeleteCategoryMarginResponse> DeleteCategoryMarginAsync(global::Msyrpc.DeleteCategoryMarginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCategoryMarginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Msyrpc.DeleteCategoryMarginResponse> DeleteCategoryMarginAsync(global::Msyrpc.DeleteCategoryMarginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCategoryMargin, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PriceComparisonServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PriceComparisonServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PriceComparisonServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllProductCategories, serviceImpl.GetAllProductCategories)
          .AddMethod(__Method_GetAllNewCategoryTypes, serviceImpl.GetAllNewCategoryTypes)
          .AddMethod(__Method_GetAllCompetitors, serviceImpl.GetAllCompetitors)
          .AddMethod(__Method_GetLoadProductComparisonInfomation, serviceImpl.GetLoadProductComparisonInfomation)
          .AddMethod(__Method_GetLoadFilteredProductComparisonInfomation, serviceImpl.GetLoadFilteredProductComparisonInfomation)
          .AddMethod(__Method_UpdateProductDescription, serviceImpl.UpdateProductDescription)
          .AddMethod(__Method_UpdateCompetitorTier, serviceImpl.UpdateCompetitorTier)
          .AddMethod(__Method_DeleteCompetitor, serviceImpl.DeleteCompetitor)
          .AddMethod(__Method_AddCompetitor, serviceImpl.AddCompetitor)
          .AddMethod(__Method_GetAllStateProductCategories, serviceImpl.GetAllStateProductCategories)
          .AddMethod(__Method_UpdateCategoryState, serviceImpl.UpdateCategoryState)
          .AddMethod(__Method_GetCategoryMargin, serviceImpl.GetCategoryMargin)
          .AddMethod(__Method_AddCategoryMargin, serviceImpl.AddCategoryMargin)
          .AddMethod(__Method_DeleteCategoryMargin, serviceImpl.DeleteCategoryMargin).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PriceComparisonServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllProductCategories, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetAllCategoryTypesRequest, global::Msyrpc.AllCategoryTypesResponse>(serviceImpl.GetAllProductCategories));
      serviceBinder.AddMethod(__Method_GetAllNewCategoryTypes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetAllNewCategoryTypesRequest, global::Msyrpc.AllNewCategoryTypesResponse>(serviceImpl.GetAllNewCategoryTypes));
      serviceBinder.AddMethod(__Method_GetAllCompetitors, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetAllCompetitorTypesRequest, global::Msyrpc.AllCompetitorTypesResponse>(serviceImpl.GetAllCompetitors));
      serviceBinder.AddMethod(__Method_GetLoadProductComparisonInfomation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse>(serviceImpl.GetLoadProductComparisonInfomation));
      serviceBinder.AddMethod(__Method_GetLoadFilteredProductComparisonInfomation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetProductComparisonRequest, global::Msyrpc.ProductComparisonResponse>(serviceImpl.GetLoadFilteredProductComparisonInfomation));
      serviceBinder.AddMethod(__Method_UpdateProductDescription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.UpdateProductDescriptionRequest, global::Msyrpc.UpdateProductDescriptionResponse>(serviceImpl.UpdateProductDescription));
      serviceBinder.AddMethod(__Method_UpdateCompetitorTier, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.UpdateCompetitorTierRequest, global::Msyrpc.UpdateCompetitorTierResponse>(serviceImpl.UpdateCompetitorTier));
      serviceBinder.AddMethod(__Method_DeleteCompetitor, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.DeleteCompetitorRequest, global::Msyrpc.DeleteCompetitorResponse>(serviceImpl.DeleteCompetitor));
      serviceBinder.AddMethod(__Method_AddCompetitor, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.AddCompetitorRequest, global::Msyrpc.AddCompetitorResponse>(serviceImpl.AddCompetitor));
      serviceBinder.AddMethod(__Method_GetAllStateProductCategories, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.AllStateCategoryTypesRequest, global::Msyrpc.AllStateCategoryTypesResponse>(serviceImpl.GetAllStateProductCategories));
      serviceBinder.AddMethod(__Method_UpdateCategoryState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.UpdateCategoryStateRequest, global::Msyrpc.UpdateCategoryStateResponse>(serviceImpl.UpdateCategoryState));
      serviceBinder.AddMethod(__Method_GetCategoryMargin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.GetCategoryMarginRequest, global::Msyrpc.GetCategoryMarginResponse>(serviceImpl.GetCategoryMargin));
      serviceBinder.AddMethod(__Method_AddCategoryMargin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.AddCategoryMarginRequest, global::Msyrpc.AddCategoryMarginResponse>(serviceImpl.AddCategoryMargin));
      serviceBinder.AddMethod(__Method_DeleteCategoryMargin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Msyrpc.DeleteCategoryMarginRequest, global::Msyrpc.DeleteCategoryMarginResponse>(serviceImpl.DeleteCategoryMargin));
    }

  }
}
#endregion
