const stateType = {
    SET_CATEGORIES:"SET_CATEGORIES",
    SET_NEW_CATEGORIES:"SET_NEW_CATEGORIES",
    SET_COMPETITORS:"SET_COMPETITORS",
    SET_COMPETITORSONE:"SET_COMPETITORSONE",
    SET_COMPETITORSTWO:"SET_COMPETITORSTWO",
    ADD_COMPETITORS:"ADD_COMPETITORS",
    SET_PRODUCTCOMPARISON:"SET_PRODUCTCOMPARISON",
    SET_STATE_CATEGORIES:"SET_STATE_CATEGORIES",
    SET_MARGIN_CATEGORIES:"SET_MARGIN_CATEGORIES",
}

export default stateType;
// export interface systemState {
//     ERROR:boolean;
//     ERROR_MESSAGE:string;
// }